spring:
  config:
    import: "optional:env[.env]"
  application:
    name: cap-D
  datasource:
    url: jdbc:mysql://cap-d-database-1.cdo0oqq22gat.ap-northeast-2.rds.amazonaws.com:3306/Skai
    username: root
    password: ${spring_SECRET_KEY}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
  mail:
    host: smtp.naver.com
    port: 465
    username: wlsaudwo295@naver.com
    password: ${mail_SECRET_KEY}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    default-encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    enabled: true
    cache: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: your-bucket-name

jwt:
  secret: ${jwt_SECRET_KEY}