spring:
  application:
    name: cap-D
  datasource:
    url: jdbc:mysql://cap-d-database-1.cdo0oqq22gat.ap-northeast-2.rds.amazonaws.com:3306/Skai
    username: root
    password: Goingmeliho012!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
